// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB062NIUVFSbrRm3B7LEj0gQqJC_5z2n-Y',
    appId: '1:841394497319:web:c692a685b6000661bceb02',
    messagingSenderId: '841394497319',
    projectId: 'qr-scanner-app-dae8e',
    authDomain: 'qr-scanner-app-dae8e.firebaseapp.com',
    storageBucket: 'qr-scanner-app-dae8e.firebasestorage.app',
    measurementId: 'G-HD4RLZ465H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpFJE3WGNrxLcQPiLbd9vlkPk739gaGTs',
    appId: '1:841394497319:android:409fa5e873363e59bceb02',
    messagingSenderId: '841394497319',
    projectId: 'qr-scanner-app-dae8e',
    storageBucket: 'qr-scanner-app-dae8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNeyAX2oHJi39Sb2i0y23lQF8mhUVaW-A',
    appId: '1:841394497319:ios:88c48918ddf54788bceb02',
    messagingSenderId: '841394497319',
    projectId: 'qr-scanner-app-dae8e',
    storageBucket: 'qr-scanner-app-dae8e.firebasestorage.app',
    iosBundleId: 'com.example.qrScannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNeyAX2oHJi39Sb2i0y23lQF8mhUVaW-A',
    appId: '1:841394497319:ios:88c48918ddf54788bceb02',
    messagingSenderId: '841394497319',
    projectId: 'qr-scanner-app-dae8e',
    storageBucket: 'qr-scanner-app-dae8e.firebasestorage.app',
    iosBundleId: 'com.example.qrScannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB062NIUVFSbrRm3B7LEj0gQqJC_5z2n-Y',
    appId: '1:841394497319:web:ea26b7d1214ddf4dbceb02',
    messagingSenderId: '841394497319',
    projectId: 'qr-scanner-app-dae8e',
    authDomain: 'qr-scanner-app-dae8e.firebaseapp.com',
    storageBucket: 'qr-scanner-app-dae8e.firebasestorage.app',
    measurementId: 'G-S3B6Y8G91T',
  );
}
